version: "3.1"
services:
  traccar:
    image: traccar/traccar:alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:8082"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/opt/traccar/logs:rw
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro
    networks:
      - default
  graphql:
    image: sunhoww/traccar_graphql:alpha
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - GUNICORN_BIND=0.0.0.0:8080
      - GUNICORN_ACCESSLOG=/var/log/traccar_graphql.log
      - GUNICORN_ERRORLOG=/var/log/traccar_graphql_error.log
      - GUNICORN_LOGLEVEL=debug
      - TRACCAR_BACKEND=http://traccar:8082
    volumes:
      - ./logs:/var/log/:rw
    depends_on:
      - traccar
    ports:
      - "8080:8080"
    networks:
      - default
