version: "3.7"

services:
  traefik:
    image: traefik:1.7-alpine
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml.development:/traefik.toml

networks:
  web:
    name: web
